// data.js
export const streams = [
    { name: "MANAGEMENT", departments: [
        "MASTER OF BUSINESS ADMINISTRATION",
        "BACHELOR OF BUSINESS ADMINISTRATION",
        "BUSINESS ADMINISTRATION WITH COMPUTER APPLICATIONS",
        "BUSINESS ADMINISTRATION WITH LOGISTICS"
    ]},
    { name: "COMPUTING", departments: [
        "COMPUTER SCIENCE",
        "INFORMATION TECHNOLOGY",
        "COMPUTER APPLICATIONS",
        "COMPUTER SCIENCE WITH COGNITIVE SYSTEMS",
        "COMPUTER SCIENCE WITH DATA ANALYTICS",
        "COMPUTER SCIENCE WITH ARTIFICIAL INTELLIGENCE & DATA SCIENCE",
        "COMPUTER SCIENCE WITH CYBER SECURITY",
        "COMPUTER TECHNOLOGY",
        "COMPUTER SCIENCE WITH DIGITAL & CYBER FORENSIC SCIENCE"
    ]},
    { name: "COMMERCE", departments: [
        "COMMERCE",
        "COMMERCE WITH COMPUTER APPLICATIONS",
        "COMMERCE WITH PROFESSIONAL ACCOUNTING",
        "COMMERCE WITH ACCOUNTING & FINANCE",
        "COMMERCE WITH BUSINESS PROCESS SERVICES",
        "COMMERCE WITH INTERNATIONAL BUSINESS",
        "COMMERCE WITH INFORMATION TECHNOLOGY",
        "COMMERCE WITH CORPORATE SECRETARYSHIP",
        "COMMERCE WITH BANKING & INSURANCE",
        "COMMERCE WITH RETAIL MARKETING",
        "COMMERCE WITH COST & MANAGEMENT ACCOUNTING"
    ]},
    { name: "SCIENCE", departments: [
        "CATERING SCIENCE & HOTEL MANAGEMENT",
        "BIOTECHNOLOGY",
        "ELECTRONICS AND COMMUNICATION SYSTEMS",
        "MATHEMATICS",
        "PHYSICS",
        "CHEMISTRY"
    ]},
    { name: "HUMANITIES", departments: [
        "ENGLISH LITERATURE",
        "MASTER OF SOCIAL WORK",
        "LANGUAGES"
    ]}
];
